### ISSUE TITLE
Can't load libraries (specifically luajava) on Windows

### ISSUE THREAD

**Issue by Col-E** [egordorichev/LastTry#1]
From the README.md

>-Djava.library.path=lib/YOUR_SYSTEM-NAME_HERE (lookup the lib folder):lib/

With the vm args `-Djava.library.path=lib/windows:lib/` the following occurs:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path`

Removing `:lib` and using `-Djava.library.path=lib/windows/` results in:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no luajava-1.1 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.keplerproject.luajava.LuaState.<clinit>(LuaState.java:86)
```

When the `luajava-1.1.dll` is dropped in the lib folder dependencies of the dll cannot be found: 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\Programming\Java\Terraria\LastTry\lib\windows\luajava-1.1.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.keplerproject.luajava.LuaState.<clinit>(LuaState.java:86)
	at org.keplerproject.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
```

Any idea on what it's missing? The exception doesn't exactly state *what* is missing, rather just that *something* is missing.

This can be temporarily ignored by commenting out the `lua` field instantiation in `LastTry.java`'s `initStatesList` method since the `lua` field isn't used anywhere else.

**Comment by egordorichev** [comment]
You are missing luajava natives. Sorry! Will remove this dependency in a moment.

**Comment by egordorichev** [comment]
Fixed by https://github.com/egordorichev/LastTry/commit/78c0ce353f6e9bc6e529e30cf7cd100fe64d717a
