### ISSUE TITLE
Unable to load images and other assets.

### ISSUE THREAD

**Issue by yadavvi91** [egordorichev/LastTry#34]
I get the following crash when running the `DesktopLauncher` via `gradle` in `IntellijIdea` (Java SE 8u121)

    Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: splash.png
    	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:147)
    	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
    	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
    	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
    	at org.egordorichev.lasttry.state.SplashState.<init>(SplashState.java:16)
    	at org.egordorichev.lasttry.LastTry.create(LastTry.java:84)
    	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
    	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
    Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: splash.png (Internal)
    	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
    	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
    	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
    	... 7 more

**Comment by egordorichev** [comment]
You should run the app from the `core/assets` directory.

**Comment by yadavvi91** [comment]
Thanks! That works.
