### ISSUE TITLE
Game crashes when clicking specific inventory boxes

### ISSUE THREAD

**Issue by PeterWathall** [egordorichev/LastTry#38]
When you click on any of the boxes to the right of the main inventory the game crashes giving this error

`Exception in thread "LWJGL Application" java.lang.NullPointerException
        at org.egordorichev.lasttry.ui.UiItemSlot.canHold(UiItemSlot.java:165)
        at org.egordorichev.lasttry.ui.UiItemSlot.onStateChange(UiItemSlot.java:196)
        at org.egordorichev.lasttry.ui.UiComponent.update(UiComponent.java:153)
        at org.egordorichev.lasttry.ui.UiComponent.render(UiComponent.java:44)
        at org.egordorichev.lasttry.ui.UiItemSlot.render(UiItemSlot.java:82)
        at org.egordorichev.lasttry.ui.UiInventory.render(UiInventory.java:237)
        at org.egordorichev.lasttry.ui.UiManager.render(UiManager.java:11)
        at org.egordorichev.lasttry.state.GamePlayState.render(GamePlayState.java:118)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at org.egordorichev.lasttry.LastTry.render(LastTry.java:166)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

**Comment by egordorichev** [comment]
What do you mean by boxes?

**Comment by egordorichev** [comment]
I know, that Inventory UI is very buggy now, but I'm working on it and exception handling.

**Comment by PeterWathall** [comment]
![boxes](https://cloud.githubusercontent.com/assets/9157578/24704380/47bcaacc-19ff-11e7-8379-87af8a8034e3.PNG)

Any of these boxes being clicked causes the game to crash

**Comment by egordorichev** [comment]
I've updated the code, it should work now. Can you check it?

**Comment by PeterWathall** [comment]
It's fixed

**Comment by egordorichev** [comment]
Thank you.

**Comment by egordorichev** [comment]
Implemented a crash handler:

```
LastTry had crashed!
-------------------
LastTry had stopped running, because it encountered a problem.

Please, copy and report the entire text to email egordorichev@gmail.com or
submit an issue https://github.com/egordorichev/LastTry/issues


--- BEGIN ERROR REPORT ---
LastTry version: v.0.3-alpha
OS: Linux (amd64) version 3.18.9-gentoo
Java version: 1.8.0_72, Oracle Corporation
Java VM version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Java VM flags: 0 total; 
Memory: 225378200 bytes (214 MB) / 243269632 bytes (232 MB) up to 3596091392 bytes (3429 MB)
Exception cause: java.lang.NullPointerException
	at org.egordorichev.lasttry.LastTry.create(LastTry.java:126)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
--- END ERROR REPORT ---
```
